# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0070_auto_20181007_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='custom_judge',
            field=models.FileField(blank=True, null=True, storage=judge.utils.problem_data.ProblemDataStorage(), upload_to=judge.models.problem_data.problem_directory_file, verbose_name='custom judge file'),
        ),
    ]
